[package]
name = "nydus_deposit"
type = "bin"
authors = ["Drone"]

[dependencies]
poseidon = { path = "../../lib/poseidon" }
poseidon_ctr_encryption = { path = "../../lib/poseidon-ctr-encryption" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
pedersen_commitments = { path = "../../lib/pedersen-commitments" }
