user_key = "0x19e573f3801c7b2e4619998342e8e305e1692184cbacd220c04198a04c36b7d2"

token_address = "0x7775e4b6f4d40be537b55b6c47e09ada025757bd"

amount = "0x32"

previous_nonce = "0x00"

main_c_tot = ["0x27a0362d6752fd3f21924e5af20aab90e2300991d3aa06bf54ca4eef4747c460", "0x0ae48d3da31a9b59fc8834c5e2c730bb078cb10c27d8737048da957e14af26f9"]

main_c_inner = ["0x1943fb00fe46c0a20b5e8882cd0185a685a68ec9cf5620c285b634647229f234", "0x19f8e89694755f4786b25a857e869bc2066b3d630a84e9e798a5de9ecb654fb6"]

main_c_outer = ["0x0bc6f794fe53f0c8704d41006c06065f765e884d12ea6841895866f6a7796568", "0x22539c9ee4342d7eaa4c5a67d5cb0c93ddf1e9e03c173e6a4e442b5d57a2b5bd"]

main_c_inner_point = ["0x20a136eb03cce0f904bab9c2916294ab43d23c9b5fc903746d599a54dab96330", "0x1debe4d888ea29dae4c3fd94df03625128198d82309fa0c40d51a5d05139b651"]

main_c_outer_point = ["0x01", "0x01", "0x01"]

personal_c_tot = ["0x258f2d36fbdce0cdd3301e19164d14d78c53f53ae06a46d25fc26c7d38ba0eaf", "0x12ff42a4f0c8bd1cdef42385814b9809e22cdd506a60193156da48282e3b06d4"]

personal_c_inner = ["0x0569c5f44e8162dc40652a81cabe0b95bca8315a81bbf3c36f0ee0dd54306bf1", "0x2e8d0ae7546577bc41ef992c9caf98c11f3a643b1dfa929d8b513dd1de02d887"]

personal_c_outer = ["0x058d7632783d25cfaf6250edd3673fc5d9af5048f75dff4d74634e7f0983fcaa", "0x02668b353cc99e55a48daf3f83c01e00208c3c44cfc3e46d9d21c4d2c1af811e"]

personal_c_inner_m = "0x64"

personal_c_outer_m = "0x00"

personal_c_outer_r = "0x7775e4b6f4d40be537b55b6c47e09ada025757bd"