user_key = "0x1234567890abcdef"

token_address = "0x02"

amount = "0x63"

previous_nonce = "0x00"

main_c_tot = ["0x111a9d19fc8566097ac237cf9420c675d1f64fe3ebcb1648214299fd8773af81", "0x2e2fd7d3fc5af6219d955c5cb3645a4e3a589491b00ab9665003514b5716e382"]

main_c_inner = ["0x2eb1dcd471c5c0e99212780748a47a91cdbad176c2806379b66f1bd0f09b75c7", "0x0fcb89d6df6792aa679e1c6e7c65f1a3193e29e8be478555577a203bef3e0be3"]

main_c_outer = ["0x08f4157f1cf75f86a4549754aa6a65dec4a984873d8254511343d892163becd7", "0x27388883c1291e2709c59a13eaa53a32c00553e5bdb9908d0817df92deb20f90"]

main_c_inner_point = ["0x19ea025eea41a3a7dd204d05b0474c4d3bb7ccfb0d873ca5b4c17d5be0a01cf6", "0x0cd08d011ac21553787ed5cf246ff9e828102197c3e74fef94ff09b2f2eff4a0"]

main_c_outer_point = ["0x15db0a12b2563d734efc5ff7272faa4994f511a98bc2736b9f63676e4b53c39d", "0x1046da9bd5fbf507ccb98bda054a14d18e4ad7ba14fb83154fc13a2d71199316", "0x029a"]

personal_c_tot = ["0x0f52e4b39ce4dad6b408f694462c0df39b79871a57dc718d051f8d467dfd81c2", "0x0ff7446d585fa4db7d237705dd257802cac7968c87318895e642392a3801aeb7"]

personal_c_inner = ["0x03bd0319d5b975efff69fcd59dfea8214db2f3df10ce9aa038d88aa8b4fe0ce4", "0x0d5f39404b8455f7632e330b0d1077f9499d791bf84ad41a1e642c699e4f5ce4"]

personal_c_outer = ["0x0cc1cba84acaee32ed15c660a866c182b244d996739b6b4f2680b1739a7d80dc", "0x2fb6b7bda80026413a9a0124f48cc15b619bf0169896498fd501faa12c12bcf5"]

personal_c_inner_m = "0x64"

personal_c_outer_m = "0x00"

personal_c_outer_r = "0x02"

receiver_public_key = ["0x0bd0e01a563a7b2bbd4b14702542d1e09ee93b4bd996f8c2d1502d05e7ac9941", "0x146a1e792e301e0c53e2422f11b3e09c9c4b58f849fc3aa1c34ea13cb8e02254"]

relay_fee_token_address = "0x03"

receiver_fee_amount = "0x01"

fee_token_personal_c_inner = ["0x0f3ca257acd1be8282961e4a15b6733fc264f4d7d1e5b305a67f0c7d0a4f8656", "0x1b0abdbb0d79ad5bda28d4731edd65623c85cb763dce21ccd840cbf8556d2d26"]

fee_token_personal_c_outer = ["0x29c89b4749ee5efa9d967c7b8f0aedfddb379f363a220192f68a5639dfa309e6", "0x20d60bb496775e0a2a088ee7443eee9e59f2d310a627faa4efd5d70b22f72f2b"]

fee_token_personal_c_inner_m = "0x0a"

fee_token_personal_c_outer_m = "0x00"

fee_token_personal_c_outer_r = "0x03"