[package]
name = "nydus_entry"
type = "bin"
authors = ["Drone"]


[dependencies]
poseidon = { path = "../../lib/poseidon" }
poseidon_ctr_encryption = { path = "../../lib/poseidon-ctr-encryption" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
pedersen_commitments = { path = "../../lib/pedersen-commitments" }
keccak = { path = "../../lib/keccak256" }
ecrecover = { path = "../../lib/ecrecover-noir" }
