[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
ignore = ["src/Verifiers/**"]

# Allow file writing for scripts
fs_permissions = [
    { access = "read-write", path = "./src" },
    { access = "read-write", path = "./src/VerifiersConst.sol" }
]



